name: scheduled-testing

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'

jobs:
  test:

    runs-on: ubuntu-latest
    